requires 'LWP::UserAgent';
requires 'LWP::Protocol::https';
requires 'HTTP::Request';
requires 'HTTP::Cookies';
requires 'HTML::Entities';
requires 'MIME::Lite';
requires 'Authen::SASL';
requires 'DBD::SQLite';
requires 'JSON::MaybeXS';
